/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MenuProduto.java
 *
 * Created on 19/06/2011, 14:51:19
 */

package Visual;

import Modelo.Produto;

/**
 *
 * @author Caio
 */
public class MenuProduto extends javax.swing.JFrame {

    private Produto p;

    /** Creates new form MenuProduto */
    public MenuProduto() {
        initComponents();
    }

    public MenuProduto(String s) {
        p = POOView.findProduto(s);

        initComponents();

        setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel5 = new java.awt.Panel();
        cadP = new javax.swing.JButton();
        isProd = new java.awt.Checkbox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nomeP = new java.awt.TextField();
        qtdP = new javax.swing.JSpinner();
        precoP = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        remP = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        panel5.setName("panel5"); // NOI18N

        cadP.setText("Cadastrar"); // NOI18N
        cadP.setName("cadP"); // NOI18N
        cadP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadPMouseClicked(evt);
            }
        });

        isProd.setLabel("Produzido"); // NOI18N
        isProd.setName("isProd"); // NOI18N
        isProd.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                isProdItemStateChanged(evt);
            }
        });

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(Modelo.POOApp.class).getContext().getResourceMap(MenuProduto.class);
        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N

        nomeP.setName("nomeP"); // NOI18N
        nomeP.setText(p.getNome());

        qtdP.setModel(new javax.swing.SpinnerNumberModel());
        qtdP.setName("qtdP"); // NOI18N
        qtdP.setValue(p.getQuantidade());

        precoP.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), null, null, Double.valueOf(1.0d)));
        precoP.setName("precoP"); // NOI18N
        precoP.setValue(p.getPreco());

        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        remP.setText(resourceMap.getString("remP.text")); // NOI18N
        remP.setName("remP"); // NOI18N
        remP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                remPMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel5Layout = new javax.swing.GroupLayout(panel5);
        panel5.setLayout(panel5Layout);
        panel5Layout.setHorizontalGroup(
            panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(panel5Layout.createSequentialGroup()
                        .addGroup(panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomeP, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(precoP, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(qtdP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))))
                    .addComponent(isProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel5Layout.createSequentialGroup()
                        .addComponent(remP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cadP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        panel5Layout.setVerticalGroup(
            panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel5Layout.createSequentialGroup()
                        .addComponent(nomeP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(precoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel5Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)))
                .addGap(10, 10, 10)
                .addGroup(panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qtdP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(2, 2, 2)
                .addComponent(isProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(cadP)
                    .addComponent(remP))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadPMouseClicked
        String s;
        Double val;
        String fail = new String();

        p.setTipo(isProd.getState());

        s = nomeP.getText();
        if(!s.equals("")) p.setNome(s);
        if(s.equals("")) fail += "\nNome";

        val = (Double)precoP.getValue();
        if(val.compareTo(0.0) > 0) p.setPreco(val.doubleValue());
        if(val.compareTo(0.0) <= 0) fail += "\nPreco";

        val = ((Integer)qtdP.getValue()).doubleValue();
        if(val.compareTo(new Double(0)) >= 0) p.setQuantidade(val.intValue());
        if(val.compareTo(new Double(0)) < 0) fail += "\nQuantidade";

        if(fail.equals("")){
            if(!POOView.addProduto(p)){
                showErro("Já existe produto com o nome: ".concat(p.getNome()));
                return;
            }

            nomeP.setText("");
            precoP.setValue(0);
            qtdP.setEnabled(true);
            qtdP.setValue(0);
            isProd.setState(false);

            POOView.plUpdate();
            return;
        }

        if(!fail.equals("")) showErro("Os seguintes campos estão incorretos:".concat(fail));
}//GEN-LAST:event_cadPMouseClicked

    private void isProdItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_isProdItemStateChanged
        qtdP.setEnabled(!isProd.getState());
}//GEN-LAST:event_isProdItemStateChanged

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    private void remPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_remPMouseClicked
        POOView.delProduto(p);
        POOView.plUpdate();
        POOView.gravarProduto();
        dispose();
    }//GEN-LAST:event_remPMouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadP;
    private java.awt.Checkbox isProd;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private java.awt.TextField nomeP;
    private java.awt.Panel panel5;
    private javax.swing.JSpinner precoP;
    private javax.swing.JSpinner qtdP;
    private javax.swing.JButton remP;
    // End of variables declaration//GEN-END:variables
    private Erro erro;

    public void showErro(String s){
        erro = new Erro(s);
        erro.setLocationRelativeTo(this);
    }
}
