/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MenuCliente.java
 *
 * Created on 19/06/2011, 14:45:04
 */

package Visual;

import Modelo.Compra;
import Modelo.Fornecedor;
import java.util.*;

/**
 *
 * @author Caio
 */
public class MenuFornecedor extends javax.swing.JFrame {

    private static Fornecedor f;

    /** Creates new form MenuCliente */
    public MenuFornecedor(String s) {
        f = POOView.findFornecedor(s);
        
        initComponents();

        vlUpdate();

        setVisible(true);
    }

    public static Compra findVenda(String s){
        return f.findCompra(s);
    }

    public static void addCompra(Compra v){
        f.addCompra(v);
    }

    public static void vlUpdate(){
        boolean teste;
        String a, t;
        listC.removeAll();
        a = findC.getText();
        for(Compra obj : f.getLC()){
            t = obj.getCode();
            teste = false;
            for(int i = 0; i < a.length(); i++){
                if(a.charAt(i) != t.charAt(i) || a.length() > t.length()){
                    teste = true;
                    break;
                }
            }
            if(!teste) listC.add(t);
        }
    }

    private MenuFornecedor() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panel1 = new java.awt.Panel();
        jButton1 = new javax.swing.JButton();
        label1 = new java.awt.Label();
        nomeF = new java.awt.TextField();
        label2 = new java.awt.Label();
        cnpjF = new java.awt.TextField();
        label4 = new java.awt.Label();
        telF = new java.awt.TextField();
        cadF = new javax.swing.JButton();
        cadC = new javax.swing.JButton();
        remF = new javax.swing.JButton();
        panel2 = new java.awt.Panel();
        findC = new java.awt.TextField();
        listC = new java.awt.List();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(Modelo.POOApp.class).getContext().getResourceMap(MenuFornecedor.class);
        jTabbedPane1.setBackground(resourceMap.getColor("jTabbedPane1.background")); // NOI18N
        jTabbedPane1.setName("jTabbedPane1"); // NOI18N

        panel1.setName("panel1"); // NOI18N

        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        label1.setName("label1"); // NOI18N
        label1.setText(resourceMap.getString("label1.text")); // NOI18N

        nomeF.setName("nomeF"); // NOI18N
        nomeF.setText(f.getNome());

        label2.setName("label2"); // NOI18N
        label2.setText(resourceMap.getString("label2.text")); // NOI18N

        cnpjF.setName("cnpjF"); // NOI18N
        cnpjF.setText(f.getCNPJ());

        label4.setName("label4"); // NOI18N
        label4.setText(resourceMap.getString("label4.text")); // NOI18N

        telF.setName("telF"); // NOI18N
        telF.setText(f.getTelefone());

        cadF.setText(resourceMap.getString("cadF.text")); // NOI18N
        cadF.setName("cadF"); // NOI18N
        cadF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadFMouseClicked(evt);
            }
        });

        cadC.setText(resourceMap.getString("cadC.text")); // NOI18N
        cadC.setName("cadC"); // NOI18N
        cadC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadCMouseClicked(evt);
            }
        });

        remF.setText(resourceMap.getString("remF.text")); // NOI18N
        remF.setName("remF"); // NOI18N
        remF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                remFMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                        .addComponent(remF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cadC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cadF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cnpjF, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                            .addComponent(nomeF, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                        .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(telF, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cnpjF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(telF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(cadF)
                    .addComponent(cadC)
                    .addComponent(remF))
                .addContainerGap())
        );

        jTabbedPane1.addTab(resourceMap.getString("panel1.TabConstraints.tabTitle"), panel1); // NOI18N

        panel2.setName("panel2"); // NOI18N

        findC.setName("findC"); // NOI18N
        findC.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                findCTextValueChanged(evt);
            }
        });

        listC.setName("listC"); // NOI18N
        listC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listCMouseClicked(evt);
            }
        });

        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(findC, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(listC, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                .addContainerGap(339, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(findC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap())
        );

        jTabbedPane1.addTab(resourceMap.getString("panel2.TabConstraints.tabTitle"), panel2); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        dispose();
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    private void cadFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadFMouseClicked
        String s;
        String fail = new String();

        s = nomeF.getText();
        if(!s.equals("")) f.setNome(s);
        if(s.equals("")) fail += "\nNome";

        s = cnpjF.getText();
        if(!s.equals("")) f.setCNPJ(s);
        if(s.equals("")) fail += "\nCNPJ";

        s = telF.getText();
        if(!s.equals("")) f.setTelefone(s);
        if(s.equals("")) fail += "\nTelefone";

        if(!fail.equals("")) showErro("Os seguintes campos estão vazios:".concat(fail));
        POOView.gravarCliente();
    }//GEN-LAST:event_cadFMouseClicked

    private void cadCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadCMouseClicked
        Compra c = new Compra();
        Calendar cal = new GregorianCalendar();
        String s = new String();
        
        cal.setTime(new Date());
        s = f.getNome() + " " + POOView.code.toString();
        POOView.code++;

        c.setData(cal);
        c.setCode(s);

        MenuCompra menuCompra = new MenuCompra(c);
        menuCompra.setLocationRelativeTo(this);

        addCompra(c);
        POOView.gravarFornecedor();
        dispose();
    }//GEN-LAST:event_cadCMouseClicked

    private void findCTextValueChanged(java.awt.event.TextEvent evt) {//GEN-FIRST:event_findCTextValueChanged
        vlUpdate();
    }//GEN-LAST:event_findCTextValueChanged

    private void listCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listCMouseClicked
        MenuCompra menuCompra;
        String s = listC.getSelectedItem();
        if(evt.getClickCount() == 2 && s != null){
            menuCompra = new MenuCompra(f.findCompra(s));
            menuCompra.setLocationRelativeTo(this);
            dispose();
        }
    }//GEN-LAST:event_listCMouseClicked

    private void remFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_remFMouseClicked
        POOView.delFornecedor(f);
        POOView.flUpdate();
        POOView.gravarCliente();
        dispose();
    }//GEN-LAST:event_remFMouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuFornecedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadC;
    private javax.swing.JButton cadF;
    private java.awt.TextField cnpjF;
    private static java.awt.TextField findC;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label4;
    private static java.awt.List listC;
    private java.awt.TextField nomeF;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private javax.swing.JButton remF;
    private java.awt.TextField telF;
    // End of variables declaration//GEN-END:variables

    private Erro erro;

    public void showErro(String s){
        erro = new Erro(s);
        erro.setLocationRelativeTo(this);
    }
}
