/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package telas.crud;

import controllers.FrmAssentoController;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.AssentoTO;

/**
 *
 * @author William
 */
public class FrmAssento extends TrabalhoFrame {

    private String[] aeronaves;
    private Character[] spnValues = {'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'};
    private FrmAssentoController controller = new FrmAssentoController();

    /**
     * Creates new form FrmAssento
     */
    public FrmAssento() {
	aeronaves = controller.getAeronaves();
	initComponents();
	tblAssentoPopulate();
	setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrAssento = new javax.swing.JScrollPane();
        tblAssento = new javax.swing.JTable();
        btnDeleteAssento = new javax.swing.JButton();
        btnSaveAssento = new javax.swing.JButton();
        btnNewAssento = new javax.swing.JButton();
        lblSearchAssento = new javax.swing.JLabel();
        txtSearchAssento = new java.awt.TextField();
        lblNewFila = new javax.swing.JLabel();
        lblNewNumero = new javax.swing.JLabel();
        spnNewNumero = new javax.swing.JSpinner();
        lblNewCodigoAeronave = new javax.swing.JLabel();
        cmbNewCodigoAeronave = new javax.swing.JComboBox();
        lblNewClasse = new javax.swing.JLabel();
        txtNewClasse = new javax.swing.JTextField();
        cmbNewFila = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblAssento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fila", "Número", "Código da Aeronave", "Classe"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAssento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAssentoMouseClicked(evt);
            }
        });
        tblAssento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblAssentoKeyPressed(evt);
            }
        });
        scrAssento.setViewportView(tblAssento);

        btnDeleteAssento.setText("Apagar");
        btnDeleteAssento.setEnabled(false);
        btnDeleteAssento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteAssentoMouseClicked(evt);
            }
        });

        btnSaveAssento.setText("Salvar");
        btnSaveAssento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveAssentoMouseClicked(evt);
            }
        });

        btnNewAssento.setText("Novo");
        btnNewAssento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNewAssentoMouseClicked(evt);
            }
        });

        lblSearchAssento.setText("Código da Aeronave");

        txtSearchAssento.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                txtSearchAssentoTextValueChanged(evt);
            }
        });

        lblNewFila.setText("Fila");

        lblNewNumero.setText("Número");

        spnNewNumero.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));
        spnNewNumero.setEnabled(false);

        lblNewCodigoAeronave.setText("Código da Aeronave");

        cmbNewCodigoAeronave.setModel(new javax.swing.DefaultComboBoxModel<String>(aeronaves));
        cmbNewCodigoAeronave.setEnabled(false);

        lblNewClasse.setText("Classe");
        lblNewClasse.setAlignmentX(0.5F);

        cmbNewFila.setModel(new javax.swing.DefaultComboBoxModel<Character>(spnValues));
        cmbNewFila.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scrAssento, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSaveAssento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteAssento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNewAssento))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblNewFila)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbNewFila, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNewNumero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnNewNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNewCodigoAeronave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbNewCodigoAeronave, 0, 109, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblNewClasse)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNewClasse, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSearchAssento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearchAssento, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblSearchAssento)
                    .addComponent(txtSearchAssento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrAssento, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewFila)
                    .addComponent(cmbNewFila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNewNumero)
                    .addComponent(spnNewNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNewCodigoAeronave)
                    .addComponent(cmbNewCodigoAeronave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewClasse)
                    .addComponent(txtNewClasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNewAssento)
                    .addComponent(btnDeleteAssento)
                    .addComponent(btnSaveAssento))
                .addContainerGap())
        );

        txtSearchAssento.getAccessibleContext().setAccessibleName("");
        spnNewNumero.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblAssentoSelect(int val) {
	cmbNewFila.setEnabled(false);
	spnNewNumero.setEnabled(false);
	cmbNewCodigoAeronave.setEnabled(false);
	btnDeleteAssento.setEnabled(true);
	tblAssento.changeSelection(val, 0, false, false);
	String codAeronave, classe;
	Character fila = ((Character) tblAssento.getValueAt(val, 0));
	Integer numero = (Integer) tblAssento.getValueAt(val, 1);
	codAeronave = (String) tblAssento.getValueAt(val, 2);
	classe = (String) tblAssento.getValueAt(val, 3);
	cmbNewFila.setSelectedItem(fila);
	spnNewNumero.setValue(numero);
	cmbNewCodigoAeronave.setSelectedItem(codAeronave);
	txtNewClasse.setText(classe);
    }

    private void tblAssentoPopulate() {
	List<AssentoTO> res = controller.find(txtSearchAssento.getText());
	DefaultTableModel modelo = (DefaultTableModel) tblAssento.getModel();
	modelo.setRowCount(0);
	if (res == null) {
	    return;
	}
	int i = 0;
	String codSub;
	for (AssentoTO assento : res) {
	    modelo.addRow(new Object[modelo.getColumnCount()]);
	    tblAssento.setValueAt(assento.getFila(), i, 0);
	    tblAssento.setValueAt(assento.getNumero(), i, 1);
	    codSub = assento.getAeronave().getCodAeronave();
	    tblAssento.setValueAt(codSub, i, 2);
	    tblAssento.setValueAt(assento.getClasse(), i, 3);
	    i++;
	}
    }

    private void txtSearchAssentoTextValueChanged(java.awt.event.TextEvent evt) {//GEN-FIRST:event_txtSearchAssentoTextValueChanged
	tblAssentoPopulate();
    }//GEN-LAST:event_txtSearchAssentoTextValueChanged

    private void tblAssentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblAssentoKeyPressed
	int val = tblAssento.getSelectedRow();
	if (evt.getID() == java.awt.event.KeyEvent.VK_DOWN) {
	    if (val <= tblAssento.getRowCount()) {
		val++;
	    }
	} else if (evt.getID() == java.awt.event.KeyEvent.VK_UP) {
	    if (val > 0) {
		val--;
	    }
	} else {
	    return;
	}
	tblAssentoSelect(val);
    }//GEN-LAST:event_tblAssentoKeyPressed

    private void tblAssentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAssentoMouseClicked
	int val = tblAssento.getSelectedRow();
	tblAssentoSelect(val);
    }//GEN-LAST:event_tblAssentoMouseClicked

    private void btnDeleteAssentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteAssentoMouseClicked
	controller.deletar((Character) cmbNewFila.getSelectedItem(), (Integer) spnNewNumero.getValue(), (String) cmbNewCodigoAeronave.getSelectedItem());
	tblAssentoPopulate();
    }//GEN-LAST:event_btnDeleteAssentoMouseClicked

    private void btnSaveAssentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveAssentoMouseClicked
	controller.salvar((Character) cmbNewFila.getSelectedItem(), (Integer) spnNewNumero.getValue(), (String) cmbNewCodigoAeronave.getSelectedItem(), (String) txtNewClasse.getText());
	tblAssentoPopulate();
    }//GEN-LAST:event_btnSaveAssentoMouseClicked

    private void btnNewAssentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewAssentoMouseClicked
	cmbNewFila.setSelectedIndex(0);
	spnNewNumero.setValue(0);
	cmbNewCodigoAeronave.setSelectedIndex(0);
	txtNewClasse.setText("");
	cmbNewFila.setEnabled(true);
	spnNewNumero.setEnabled(true);
	cmbNewCodigoAeronave.setEnabled(true);
	btnDeleteAssento.setEnabled(false);
    }//GEN-LAST:event_btnNewAssentoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/*
	 * Set the Nimbus look and feel
	 */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
	 * If Nimbus (introduced in Java SE 6) is not available, stay with the
	 * default look and feel. For details see
	 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(FrmAssento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(FrmAssento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(FrmAssento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(FrmAssento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>

	/*
	 * Create and display the form
	 */
	java.awt.EventQueue.invokeLater(new Runnable() {

	    public void run() {
		new FrmAssento().setVisible(true);
	    }
	});
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteAssento;
    private javax.swing.JButton btnNewAssento;
    private javax.swing.JButton btnSaveAssento;
    private javax.swing.JComboBox cmbNewCodigoAeronave;
    private javax.swing.JComboBox cmbNewFila;
    private javax.swing.JLabel lblNewClasse;
    private javax.swing.JLabel lblNewCodigoAeronave;
    private javax.swing.JLabel lblNewFila;
    private javax.swing.JLabel lblNewNumero;
    private javax.swing.JLabel lblSearchAssento;
    private javax.swing.JScrollPane scrAssento;
    private javax.swing.JSpinner spnNewNumero;
    private javax.swing.JTable tblAssento;
    private javax.swing.JTextField txtNewClasse;
    private java.awt.TextField txtSearchAssento;
    // End of variables declaration//GEN-END:variables
}
