/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package telas.crud;

import controllers.FrmCompanhiaController;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.CompanhiaTO;

/**
 *
 * @author William
 */
public class FrmCompanhia extends TrabalhoFrame {

    private FrmCompanhiaController controller = new FrmCompanhiaController();
    
    /**
     * Creates new form FrmCompanhia
     */
    public FrmCompanhia() {
        initComponents();
	tblCompanhiaPopulate();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrCompanhia = new javax.swing.JScrollPane();
        tblCompanhia = new javax.swing.JTable();
        btnDeleteCompanhia = new javax.swing.JButton();
        btnSaveCompanhia = new javax.swing.JButton();
        btnNewCompanhia = new javax.swing.JButton();
        lblSearchCompanhia = new javax.swing.JLabel();
        txtSearchCompanhia = new java.awt.TextField();
        lblNewSigla = new javax.swing.JLabel();
        txtNewSigla = new javax.swing.JTextField();
        lblNewNome = new javax.swing.JLabel();
        txtNewNome = new javax.swing.JTextField();
        lblNewNomeFantasia = new javax.swing.JLabel();
        txtNewNomeFantasia = new javax.swing.JTextField();
        lblNewPais = new javax.swing.JLabel();
        txtNewPais = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblCompanhia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sigla", "Nome", "Nome Fantasia", "País"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCompanhia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCompanhiaMouseClicked(evt);
            }
        });
        tblCompanhia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblCompanhiaKeyPressed(evt);
            }
        });
        scrCompanhia.setViewportView(tblCompanhia);

        btnDeleteCompanhia.setText("Apagar");
        btnDeleteCompanhia.setEnabled(false);
        btnDeleteCompanhia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteCompanhiaMouseClicked(evt);
            }
        });

        btnSaveCompanhia.setText("Salvar");
        btnSaveCompanhia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveCompanhiaMouseClicked(evt);
            }
        });

        btnNewCompanhia.setText("Novo");
        btnNewCompanhia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNewCompanhiaMouseClicked(evt);
            }
        });

        lblSearchCompanhia.setText("Pesquise pela Sigla");

        txtSearchCompanhia.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                txtSearchCompanhiaTextValueChanged(evt);
            }
        });

        lblNewSigla.setText("Sigla");

        txtNewSigla.setEnabled(false);

        lblNewNome.setText("Nome");

        lblNewNomeFantasia.setText("Nome Fantasia");

        lblNewPais.setText("País");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scrCompanhia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblSearchCompanhia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearchCompanhia, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblNewSigla)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNewSigla, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNewNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNewNome, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblNewNomeFantasia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNewNomeFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNewPais)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNewPais, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDeleteCompanhia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSaveCompanhia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNewCompanhia)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblSearchCompanhia)
                    .addComponent(txtSearchCompanhia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrCompanhia, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewSigla)
                    .addComponent(txtNewSigla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNewNome)
                    .addComponent(txtNewNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewNomeFantasia)
                    .addComponent(txtNewNomeFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNewPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNewPais))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNewCompanhia)
                    .addComponent(btnSaveCompanhia)
                    .addComponent(btnDeleteCompanhia))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblCompanhiaSelect(int val) {
	txtNewSigla.setEnabled(false);
	btnDeleteCompanhia.setEnabled(true);
	tblCompanhia.changeSelection(val, 0, false, false);
	String sigla, nome, nomeFantasia, pais;
	sigla = (String) tblCompanhia.getValueAt(val, 0);
	nome = (String) tblCompanhia.getValueAt(val, 1);
	nomeFantasia = (String) tblCompanhia.getValueAt(val, 2);
	pais = (String) tblCompanhia.getValueAt(val, 3);
	txtNewSigla.setText(sigla);
	txtNewNome.setText(nome);
	txtNewNomeFantasia.setText(nomeFantasia);
	txtNewPais.setText(pais);
    }

    private void tblCompanhiaPopulate() {
	List<CompanhiaTO> res = controller.find(txtSearchCompanhia.getText());
	DefaultTableModel modelo = (DefaultTableModel) tblCompanhia.getModel();
	modelo.setRowCount(0);
	if (res == null) {
	    return;
	}
	int i = 0;
	for (CompanhiaTO companhia : res) {
	    modelo.addRow(new Object[modelo.getColumnCount()]);
	    tblCompanhia.setValueAt(companhia.getSigla(), i, 0);
	    tblCompanhia.setValueAt(companhia.getNome(), i, 1);
	    tblCompanhia.setValueAt(companhia.getNomeFantasia(), i, 2);
	    tblCompanhia.setValueAt(companhia.getPais(), i, 3);
	    i++;
	}
    }
    
    private void btnNewCompanhiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewCompanhiaMouseClicked
	txtNewSigla.setText("");
	txtNewNome.setText("");
	txtNewNomeFantasia.setText("");
	txtNewPais.setText("");
	txtNewSigla.setEnabled(true);
	btnDeleteCompanhia.setEnabled(false);
    }//GEN-LAST:event_btnNewCompanhiaMouseClicked

    private void btnSaveCompanhiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveCompanhiaMouseClicked
	controller.salvar(txtNewSigla.getText(), txtNewNome.getText(), txtNewNomeFantasia.getText(), txtNewPais.getText());
	tblCompanhiaPopulate();
    }//GEN-LAST:event_btnSaveCompanhiaMouseClicked

    private void btnDeleteCompanhiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteCompanhiaMouseClicked
	controller.deletar(txtNewSigla.getText());
	tblCompanhiaPopulate();
    }//GEN-LAST:event_btnDeleteCompanhiaMouseClicked

    private void txtSearchCompanhiaTextValueChanged(java.awt.event.TextEvent evt) {//GEN-FIRST:event_txtSearchCompanhiaTextValueChanged
	tblCompanhiaPopulate();
    }//GEN-LAST:event_txtSearchCompanhiaTextValueChanged

    private void tblCompanhiaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblCompanhiaKeyPressed
	int val = tblCompanhia.getSelectedRow();
	if (evt.getID() == java.awt.event.KeyEvent.VK_DOWN) {
	    if (val <= tblCompanhia.getRowCount()) {
		val++;
	    }
	} else if (evt.getID() == java.awt.event.KeyEvent.VK_UP) {
	    if (val > 0) {
		val--;
	    }
	} else {
	    return;
	}
	tblCompanhiaSelect(val);
    }//GEN-LAST:event_tblCompanhiaKeyPressed

    private void tblCompanhiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCompanhiaMouseClicked
	int val = tblCompanhia.getSelectedRow();
	tblCompanhiaSelect(val);
    }//GEN-LAST:event_tblCompanhiaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCompanhia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCompanhia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCompanhia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCompanhia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FrmCompanhia().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteCompanhia;
    private javax.swing.JButton btnNewCompanhia;
    private javax.swing.JButton btnSaveCompanhia;
    private javax.swing.JLabel lblNewNome;
    private javax.swing.JLabel lblNewNomeFantasia;
    private javax.swing.JLabel lblNewPais;
    private javax.swing.JLabel lblNewSigla;
    private javax.swing.JLabel lblSearchCompanhia;
    private javax.swing.JScrollPane scrCompanhia;
    private javax.swing.JTable tblCompanhia;
    private javax.swing.JTextField txtNewNome;
    private javax.swing.JTextField txtNewNomeFantasia;
    private javax.swing.JTextField txtNewPais;
    private javax.swing.JTextField txtNewSigla;
    private java.awt.TextField txtSearchCompanhia;
    // End of variables declaration//GEN-END:variables
}
