/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package telas.crud;

import dal.AeronaveDAL;
import dal.AssentoDAL;
import dal.DisponibilizaDAL;
import dal.InstanciaDAL;
import java.awt.HeadlessException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.AeronaveTO;
import model.AssentoTO;
import model.InstanciaTO;

/**
 *
 * @author william.okano
 */
public class FrmCadInstancia extends TrabalhoFrame {

    private void preencheDadosAeronave() {
        cmbAeronave.removeAllItems();
        ArrayList<AeronaveTO> aeronaves = (ArrayList<AeronaveTO>) AeronaveDAL.getInstance().findAll("");
        for (AeronaveTO aero : aeronaves) {
            cmbAeronave.addItem(aero);
        }
    }

    public FrmCadInstancia() {
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        initComponents();
        preencheDadosAeronave();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtIdTrecho = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtData = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmbAeronave = new javax.swing.JComboBox();
        btnCadastrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID Trecho");

        txtIdTrecho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdTrechoActionPerformed(evt);
            }
        });

        jLabel2.setText("Data");

        jLabel3.setText("Aeronave");

        cmbAeronave.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIdTrecho)
                            .addComponent(txtData)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbAeronave, 0, 140, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIdTrecho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbAeronave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCadastrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdTrechoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdTrechoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdTrechoActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        String data = txtData.getText().trim();
        Integer id_trecho = !txtIdTrecho.getText().trim().isEmpty() ? Integer.parseInt(txtIdTrecho.getText().trim()) : -1;
        AeronaveTO aero = (AeronaveTO) cmbAeronave.getSelectedItem();
        String cod_aeronave = aero.getCodAeronave();
        SimpleDateFormat dtFormat = new SimpleDateFormat("dd/MM/yyyy");
        SimpleDateFormat dtFormatEUA = new SimpleDateFormat("yyyy-MM-dd");
        Date data_ = null;
        try {
            dtFormat.setLenient(true);
            data_ = dtFormat.parse(data);
            data = dtFormatEUA.format(data_);
            //Verifico se já não tem instância nesta data
            InstanciaTO instanciaTO = InstanciaDAL.getInstance().find(data, id_trecho.intValue());
            if (instanciaTO != null) {
                System.out.println("Já existe esta instância.");
                System.out.println("Data: " + data);
                System.out.println("ID Trecho: " + id_trecho);
                JOptionPane.showMessageDialog(null, "Já existe uma instância para esta data ( :");
            } else {
                //Recupero todos os assentos de uma aeronave
                ArrayList<AssentoTO> assentos = AssentoDAL.getInstance().findAll(cod_aeronave);
                try {
                    //Crio uma instância para este trecho
                    instanciaTO = InstanciaDAL.getInstance().create(id_trecho.intValue(), data);
                    for (AssentoTO assento : assentos) {
                        DisponibilizaDAL.create(assento.getFila(), assento.getNumero(), assento.getAeronave().getCodAeronave(), instanciaTO.getDate(), instanciaTO.getTrecho().getIdTrecho());
                    }
                    JOptionPane.showMessageDialog(null, "Instâncias criadas e disponibilizadas!", "Atenção", JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                    FrmReserva f = new FrmReserva();
                    f.setLocationRelativeTo(null);
                    f.setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(FrmCadInstancia.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, ex.toString());
                }
            }
        } catch (ParseException | HeadlessException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCadInstancia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCadInstancia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCadInstancia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCadInstancia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCadInstancia().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    public javax.swing.JComboBox cmbAeronave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JTextField txtData;
    public javax.swing.JTextField txtIdTrecho;
    // End of variables declaration//GEN-END:variables
}
